# Generated by Django 4.2.4 on 2023-09-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
